### PR TITLE
using java 8, restored features, version to 1.3.0-alpha-4

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by proninyaroslav** [comment]
There seems to be problems with naming a `.so` libraries
Снимок экрана от 2020-04-05 12-03-33

```
2020-04-05 11:59:10.072 5112-5112/org.proninyaroslav.libretorrent.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.proninyaroslav.libretorrent.debug, PID: 5112
    java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/aldenml/libtorrent4j
        at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:28)
        at org.libtorrent4j.swig.libtorrent_jni.new_posix_wrapper(Native Method)
        at org.libtorrent4j.swig.posix_wrapper.<init>(posix_wrapper.java:75)
        at org.proninyaroslav.libretorrent.core.system.LibTorrentSafAdapter.<init>(LibTorrentSafAdapter.java:41)
        at org.proninyaroslav.libretorrent.MainApplication.onCreate(MainApplication.java:57)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.proninyaroslav.libretorrent.debug-mJuQf2PFTqDZsjduRtloQA==/base.apk"],nativeLibraryDirectories=[/data/app/org.proninyaroslav.libretorrent.debug-mJuQf2PFTqDZsjduRtloQA==/lib/x86_64, /data/app/org.proninyaroslav.libretorrent.debug-mJuQf2PFTqDZsjduRtloQA==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libtorrent4j.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:23)
        at org.libtorrent4j.swig.libtorrent_jni.new_posix_wrapper(Native Method) 
        at org.libtorrent4j.swig.posix_wrapper.<init>(posix_wrapper.java:75) 
        at org.proninyaroslav.libretorrent.core.system.LibTorrentSafAdapter.<init>(LibTorrentSafAdapter.java:41) 
        at org.proninyaroslav.libretorrent.MainApplication.onCreate(MainApplication.java:57) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-04-05 11:59:10.072 5112-5112/org.proninyaroslav.libretorrent.debug E/ACRA: ACRA caught a LinkageError for org.proninyaroslav.libretorrent.debug
    java.lang.LinkageError: Look for your architecture binary instructions at: https://github.com/aldenml/libtorrent4j
        at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:28)
        at org.libtorrent4j.swig.libtorrent_jni.new_posix_wrapper(Native Method)
        at org.libtorrent4j.swig.posix_wrapper.<init>(posix_wrapper.java:75)
        at org.proninyaroslav.libretorrent.core.system.LibTorrentSafAdapter.<init>(LibTorrentSafAdapter.java:41)
        at org.proninyaroslav.libretorrent.MainApplication.onCreate(MainApplication.java:57)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.proninyaroslav.libretorrent.debug-mJuQf2PFTqDZsjduRtloQA==/base.apk"],nativeLibraryDirectories=[/data/app/org.proninyaroslav.libretorrent.debug-mJuQf2PFTqDZsjduRtloQA==/lib/x86_64, /data/app/org.proninyaroslav.libretorrent.debug-mJuQf2PFTqDZsjduRtloQA==/base.apk!/lib/x86_64, /system/lib64, /system/product/lib64]]] couldn't find "libtorrent4j.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.libtorrent4j.swig.libtorrent_jni.<clinit>(libtorrent_jni.java:23)
        at org.libtorrent4j.swig.libtorrent_jni.new_posix_wrapper(Native Method) 
        at org.libtorrent4j.swig.posix_wrapper.<init>(posix_wrapper.java:75) 
        at org.proninyaroslav.libretorrent.core.system.LibTorrentSafAdapter.<init>(LibTorrentSafAdapter.java:41) 
        at org.proninyaroslav.libretorrent.MainApplication.onCreate(MainApplication.java:57) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-04-05 11:59:10.119 5112-5112/org.proninyaroslav.libretorrent.debug I/Process: Sending signal. PID: 5112 SIG: 9
```

**Comment by aldenml** [comment]
right, I forgot to remove the version from the binaries. That was because of an old bug in android, but I expect that should be fixed by now. I will release another beta.

**Comment by proninyaroslav** [comment]
All previous versions of `libtorrent4j` and `jlibtorrent` had a version number in the name and it worked, maybe the `-alpha-x` suffix is the reason, I don’t know

**Comment by proninyaroslav** [comment]
`1.2.3.0`, for example:

Снимок экрана от 2020-04-05 20-50-07

**Pull request merged**
