### PR TITLE
preparing release of first alpha for 1.3.0

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by proninyaroslav** [comment]
Nice job. Will alpha be available on Maven? I would like to test it.

**Comment by aldenml** [comment]
hi @proninyaroslav, yes, it will be. btw, I removed all the code related to the POSIX layer, I know you need it, but I'm not sure about bringing it back, also, now the min version for android API is 24, I imagine that for when `libtorrent` master is stable, this is not a problem.

**Comment by proninyaroslav** [comment]
@aldenml 
Bad news. Without POSIX, it will be impossible to support the app in the future, since Google prohibits the use of the classic filesystem starting with target API 29, instead proposing to use only `SAF` or `Android/data` folder. The focus of `libtorrent` on files only, excluding access to the file descriptor, will make impossible to use it on Android in the near future.

**Comment by aldenml** [comment]
@proninyaroslav I see, well, I will think about it, it just that the hack is so ugly and fragile

**Comment by proninyaroslav** [comment]
@aldenml Thank you. I agree that it's ugly, but without it I can not imagine what I should do: D

**Pull request merged**
