### PR TITLE
update to libtorrent master HEAD, version 2.1.0-27

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by proninyaroslav** [comment]
@aldenml 
When to expect publication in maven?

**Comment by aldenml** [comment]
Hi @proninyaroslav!, Ideally this week

**Comment by proninyaroslav** [comment]
Thank you, hope for a release soon

**Comment by aldenml** [comment]
@proninyaroslav took me a bit longer :), it's published now

**Comment by proninyaroslav** [comment]
@aldenml 
Can you tell me how to replace the `TorrentInfo::bencode` method? I see that it has been removed.

**Comment by aldenml** [comment]
@proninyaroslav good question, here it is the answer from Arvidn: https://github.com/arvidn/libtorrent/issues/7200

Let me know if you need help with doing that in java.

**Comment by proninyaroslav** [comment]
@aldenml 
Thank you. I realized that this will have to be done in an asynchronous manner through `AlertListener`, which of course is not as good as before)

**Comment by proninyaroslav** [comment]
@aldenml 
The only difficulty I faced: let's say I got the magnet torrent bencode in the AlertListener
```Java
byte_vector bytes = libtorrent.write_resume_data(((SaveResumeDataAlert) alert).params().swig()).bencode();
```
but now I can't add trackers and url seeds that a magnet link can contain. Previously, I used a `create_torrent` class for this, passing bencode and `add_torrent_params` to it, but now it has also changed its API. Is there a way to edit the bencode obtained in this way?

**Comment by aldenml** [comment]
@proninyaroslav totally agree that now it a lot more difficult to achieve the same. I did try to recreate the  feature but was too much hack. With enough time I think something can be done, just not ETA from me.

**Comment by proninyaroslav** [comment]
And also a resume data doesn't seem to contain trackers and url seeds of the magnet, despite the `SAVE_INFO_DICT` flag.

**Comment by proninyaroslav** [comment]
@aldenml 
> And also a resume data doesn't seem to contain trackers and url seeds of the magnet, despite the `SAVE_INFO_DICT` flag.

Yes, it looks like it's broken in the new version. I thought my magnet fetching code was the problem, but I also checked the default `SessionManager::fetchMagnet` method and it returns an empty list of trackers and url seeds even if the magnet contains trackers. At the same time, `TorrentInfo::bencode` in the old version correctly returned a list of trackers and url seeds.

**Comment by aldenml** [comment]
I see, please, create an issue and I will look at it

**Comment by proninyaroslav** [comment]
https://github.com/aldenml/libtorrent4j/issues/231

**Comment by proninyaroslav** [comment]
@aldenml 
Hi! Do you have any news? I would like to release my app, but had to be delayed due to this issue https://github.com/aldenml/libtorrent4j/issues/231

**Comment by aldenml** [comment]
Hi @proninyaroslav, I will try to dedicate some time this weekend.

**Pull request merged**
